### ISSUE TITLE
Dataset problem about msl datasets

### ISSUE THREAD

**Issue by yyyyybb567** [d-ailin/GDN#15]
Hello, thank you very much for your work. This paper and code have inspired me a lot. Thank you very much!

In the process of code reproduction, I met some problems. I am not quite clear about the source of MSL data set, and I wonder if you could give a more detailed explanation. I am a beginner of Python and neural networks. I am a novice, so I can't read the code, so I use your code as a black box. For MSL data sets, the F1 score is about 0.88-0.90 after multiple runs. I made some boring attempts to keep the label of your data set unchanged, change all other data to RAND (), random number, and then run the same F1 score as 0.88-0.90. I'm not quite sure why, and I wonder if you could enlighten me. Thank you very much.

In addition, I am really stupid and can't read the code, so I may encounter many problems later. I sincerely want to get in touch with you and hope to get some advice from you. I didn't find your email address, so I don't know how to contact you easily. My email is 21s105128@stu.hit.edu.cn and I look forward to contacting you.

**Comment by d-ailin** [comment]
You could just take the MSL data as demo/toy data to help check if the environment or setup is ready for running the repo bug-free. In addition, you could follow the demo data and replace it with your custom data. 

Everyone once started from a novice so that is totally fine. Maybe I could not help with the very detailed problems but if you have any other issues or questions with the paper, you could contact me at ailin@comp.nus.edu.sg.

Thanks and Good luck :)

**Comment by therealljia** [comment]
Hi, I found that my code also came out with results that stayed consistent, although I tried to change some parameters. May I ask if you solved this problem
