### ISSUE TITLE
What's the meaning of negative total_error_scores?

### ISSUE THREAD

**Issue by caixun99** [d-ailin/GDN#22]
If I got a very big total_error_score in one dimension,what's the meaning?

**Comment by d-ailin** [comment]
I think that represents a large deviation in that dimension, which indicates there might exist anomalies in such a dimension.

**Comment by caixun99** [comment]
But I get confused about the negative total_error_scores,maybe I should use abs function?

**Comment by d-ailin** [comment]
I think it is no need to use abs function here. As the total_error_scores is computed from the test deviation for each timestamp and median test deviation, the deviation itself is computed as the absolute value. The negative total_error_scores mean the deviation are smaller than the median, so that the anomaly scores are smaller, which is reasonable.

**Comment by d-ailin** [comment]
Closing. Feel free to reopen if there is any further question.
