### ISSUE TITLE
Real time detection issue

### ISSUE THREAD

**Issue by ELMERWANG** [d-ailin/GDN#83]
Hi, thanks for your valuable work! I have achieved similar model performance result. However, I have few questions related to the real time detection, much appreciate it if you could clarify :)

In the paper, it mentions that 'robust normalization of the error values of each sensor'. The normalization parameters median and inter-quartile range are calculated for evaluation set and testing set separately, which means I only can start doing anomaly detection after the GDN model predicts all the data in the testing dataset (i.e., after prediction for all the testing data, it calculates the residual, then calculate the mean and IQR, and use these to normalize the residual, then comparing with the threshsold to determine anomaly or normal). Hence, this method is not a real time detection method, right? (please correct me if I am wrong)

My question is that, is it possible to make it real time? e.g., use the mean and IQR of the evaluation set residuals to normalize the residual of the testing set data. I have tried using the mean and IQR of the evaluation set prediction residuals to normalize the testing set prediction residual, below is the result I got. Just curious, because the threshold is obtained from the evaluation set, why using the mean and IQR of the evaluation set residual to normalize the residuals of the testing dataset can result in a poor detection result?

F1 score:  0.007254261878853826
Precision:  0.9523809523809523
Recall:  0.0036409976333515383

Thanks and really looking forward to hearing from you!!

**Comment by d-ailin** [comment]
Thanks for your interest in our work.

Yes, the current method is not a real time detection method as it requires normalization based on the testing set. From my experience, the great result differences between using evaluation and testing set is mainly due to the situation when testing data have large distribution shift with the evaluation data. For example, imagine that there is a sensor behaving totally differently in evaluation data and test data, using the evaluation data to do normalization for the test data will probably induce irregular values and hence leads to inaccurate forecasting or predictions. But if the evaluation data and test data is guaranteed to no or little distribution shift, the results should be similar whenever evaluation or test data is used for normalization. 

Hope it clarifies :)

**Comment by dsn2024uq** [comment]
Hi Ailin, much appreciate it for your quick response! And yea thanks for your explanation, it is much clear now :)

Just two more questions: If this method is not a real time detection method, are the methods that used to compare with GDN also non-real-time detection methods? e.g., MAD-GAN, LSTM-VAE, and DAGMM in table 2?

The second question is: I am thinking that non-real-time detection has its opportunity of obtaining an overview of the residuals statistics before making the decision, so generally speaking, the observed statistics can be beneficial to improve the anomaly detection performance comparing with real-time detection methods, right?

Thank you very much for your time and looking forward to hearing from you!

**Comment by ELMERWANG** [comment]
Hi Ailin, much appreciate it for your quick response! And yea thanks for your explanation, it is much clear now :)

Just two more questions: If this method is not a real time detection method, are the methods that used to compare with GDN also non-real-time detection methods? e.g., MAD-GAN, LSTM-VAE, and DAGMM in table 2?

The second question is: I am thinking that non-real-time detection has its opportunity of obtaining an overview of the residuals statistics before making the decision, so generally speaking, the observed statistics can be beneficial to improve the anomaly detection performance comparing with real-time detection methods, right?

Thank you very much for your time and looking forward to hearing from you!

**Comment by d-ailin** [comment]
Glad to hear that it clarifies :)

1) If looking into the implementation of MAD-GAN (https://github.com/LiDan456/MAD-GANs/blob/3139a73a4112d3f3f18182c9a6cdc2c671e7cfe8/data_utils.py#L143), they have also adopted the statistics from test set to process, so it is not strictly real-time detection. I think DAGMM should be able to detect based on single-point data and without using testing statistics (based on its paper) and LSTM-VAE might be a bit hard to say as they would usually use a sliding window as input and check the reconstruction error based on the sliding window to select anomalous points, which means that they might require data from T+k time step to decide if T time step has error or not.

2) Sure, online detection is a more difficult and challenging task especially when no further information given. It is hard to know if a sudden change is an anomaly or just due to some normal operation but not recorded in the training/evaluation data if no information is given. Knowing some statistics is a way to mitigate this issue and it could also be potentially addressed by knowing some knowledge(e.g., informed by an expert that a manual operation is performed).

**Comment by ELMERWANG** [comment]
Thanks Ailin for your prompt and detailed explanation, hope you have a nice rest of the week!
